name: snake_rl
channels:
  - conda-forge
  - defaults
  - pytorch # 添加 pytorch 频道以获得官方的 PyTorch CPU conda 包
dependencies:
  - python=3.10
  - pip
  - numpy
  - matplotlib
  - jupyter
  - tensorboard
  - pip:
    - torch==2.3.0  # 指定与DirectML兼容的版本
    - torch-directml
    - gymnasium[atari,accept-rom-license]
    - ale-py
    - opencv-python
    - pillow
    - tqdm
