name: snake_rl
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy>=2.0
  - matplotlib
  - jupyter
  - tensorboard
  - pytorch
  - pip:
    - gymnasium[atari,accept-rom-license]
    - ale-py
    - opencv-python>=4.10.0.84
    - pillow
    - tqdm
