name: snake_rl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - matplotlib
  - jupyter
  - tensorboard
  - pip:
    - torch
    - torchvision
    - torchaudio
    - gymnasium[atari,accept-rom-license]
    - ale-py
    - opencv-python
    - pillow
    - tqdm